[package]
name = "next_prime"
version = "0.1.0"
authors = ["Michaël Lévesque-Dion <mlevesquedion@gmail.com>"]
edition = "2018"
description = "A function that returns the next prime greater than or equal to its argument"
license = "MIT"

[dependencies]